// <auto-generated />
using System;
using Fintranet.TaxCalculation.Repository.Implimentation;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fintranet.TaxCalculation.Repository.Implimentation.Migrations.ApplicationDb
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240123090103_initialMigrationForApplicationDbContext")]
    partial class initialMigrationForApplicationDbContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Fintranet.TaxCalculation.Model.Entities.Base.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 1, 23, 12, 31, 2, 536, DateTimeKind.Local).AddTicks(5161));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 1, 23, 12, 31, 2, 536, DateTimeKind.Local).AddTicks(5311));

                    b.HasKey("Id");

                    b.ToTable("City");
                });

            modelBuilder.Entity("Fintranet.TaxCalculation.Model.Entities.Base.InitialSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 1, 23, 12, 31, 2, 535, DateTimeKind.Local).AddTicks(8898));

                    b.Property<string>("FreeTaxDates")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("freeTaxDates");

                    b.Property<string>("FreeTaxMonth")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("freeTaxMonth");

                    b.Property<string>("FreeTaxVehicleTypes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("freeTaxVehicleTypes");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<double?>("MaximumTaxPerDay")
                        .HasColumnType("float");

                    b.Property<bool>("TaxFreeOnHolidays")
                        .HasColumnType("bit");

                    b.Property<string>("TaxPrices")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("taxPrices");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 1, 23, 12, 31, 2, 535, DateTimeKind.Local).AddTicks(9026));

                    b.HasKey("Id");

                    b.HasIndex("CityId")
                        .IsUnique();

                    b.ToTable("InitialSetting");
                });

            modelBuilder.Entity("Fintranet.TaxCalculation.Model.Entities.Base.VehicleTaxDate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 1, 23, 12, 31, 2, 535, DateTimeKind.Local).AddTicks(8198));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 1, 23, 12, 31, 2, 535, DateTimeKind.Local).AddTicks(8302));

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("VehicleTaxDate");
                });

            modelBuilder.Entity("Fintranet.TaxCalculation.Model.Entities.Base.VehicleType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 1, 23, 12, 31, 2, 535, DateTimeKind.Local).AddTicks(7823));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTaxFree")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 1, 23, 12, 31, 2, 535, DateTimeKind.Local).AddTicks(7930));

                    b.HasKey("Id");

                    b.ToTable("VehicleTypes");
                });

            modelBuilder.Entity("Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 1, 23, 12, 31, 2, 535, DateTimeKind.Local).AddTicks(7331));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 1, 23, 12, 31, 2, 535, DateTimeKind.Local).AddTicks(7541));

                    b.Property<Guid?>("VehicleTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("Fintranet.TaxCalculation.Model.Entities.Base.InitialSetting", b =>
                {
                    b.HasOne("Fintranet.TaxCalculation.Model.Entities.Base.City", "City")
                        .WithOne("InitialSetting")
                        .HasForeignKey("Fintranet.TaxCalculation.Model.Entities.Base.InitialSetting", "CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Vehicle", b =>
                {
                    b.HasOne("Fintranet.TaxCalculation.Model.Entities.Base.VehicleType", "VehicleType")
                        .WithMany("Vehicles")
                        .HasForeignKey("VehicleTypeId");

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("Fintranet.TaxCalculation.Model.Entities.Base.City", b =>
                {
                    b.Navigation("InitialSetting");
                });

            modelBuilder.Entity("Fintranet.TaxCalculation.Model.Entities.Base.VehicleType", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
